---
- name: Update ansible slave node with python and pip
  hosts: ansibleslave
  remote_user: ubuntu
  sudo: yes
  vars:
    DOCKER_COMPOSE_VERSION: "1.29.2"
    
  tasks:
  - name: Update Ubuntu
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Python3 latest version
    apt:
      name: python3
      state: present

  - name: Install python3-apt
    apt:  
      name: python3-apt
      state: present
  
  - name: Install python setuptools 
    apt:  
      name: python3-setuptools
      state: present
      
  - name: virtual environment for python
    pip:
      name: virtualenv
  
  - name: Update apt packages
    apt:
      update_cache: "yes"
      cache_valid_time: 3600

  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Test Docker with hello world example
    shell: "docker run hello-world"
    register: hello_world_output

  - name: Show output of hello word example
    debug:
      msg: "Container Output: {{hello_world_output.stdout}}"

  - name: Install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64
      dest: "/usr/local/bin/docker-compose"
      mode: 0755

  - name: Reboot server in order for changes to take place
    shell: "sleep 1 && reboot"
    async: 1
    poll: 0